const products = [
  {
    id: "1",
    image: "/p1.jpeg",
    category: "Men's Clothing",
    name: "Classic Cotton T-Shirt",
    rating: 4,
    price: 199.0,
  },
  {
    id: "2",
    image: "/p2.jpeg",
    category: "Men's Clothing",
    name: "Slim Fit Denim Jeans",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },
  {
    id: "3",
    image: "/kids3.webp",
    category: "Kids' Clothing",
    name: "Printed Kids Hoodie",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },
  {
    id: "4",
    image: "/p4.jpeg",
    category: "Women's Clothing",
    name: "Summer Floral Dress",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },
  {
    id: "5",
    image: "/p5.jpeg",
    category: "Men's Clothing",
    name: "Casual Cotton Shirt",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },
  {
    id: "6",
    image: "/kids2.webp",
    category: "Kids' Clothing",
    name: "Boys' Denim Jacket",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },
  {
    id: "7",
    image: "/p3.jpeg",
    category: "Women's Clothing",
    name: "Knitted Wool Sweater",
    rating: 5,
    price: 275.0,
    oldPrice: 399.0,
    discount: "-25%",
  },

];

export default products;
